services:
  # general settings
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Slavlee\PopupPower\:
    resource: '../Classes/*'

  Slavlee\PopupPower\Domain\Service\ClosestConfigurationService:
    public: true
